apiVersion: 1

datasources:
  - name: Vela Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: vela_user
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: vela
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
