// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vela.Worker.Data;

#nullable disable

namespace Vela.Worker.Data.Migrations
{
    [DbContext(typeof(VelaDbContext))]
    [Migration("20260604084146_RenameXScoreColumn")]
    partial class RenameXScoreColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vela.Worker.Data.AlertEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualPriceAtTimeOfAlert")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_price_at_time_of_alert");

                    b.Property<bool?>("CanAverage")
                        .HasColumnType("boolean")
                        .HasColumnName("can_average");

                    b.Property<string>("ContractDescription")
                        .HasColumnType("text")
                        .HasColumnName("contract_description");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("Expiration")
                        .HasColumnType("text")
                        .HasColumnName("expiration");

                    b.Property<string>("FormattedLength")
                        .HasColumnType("text")
                        .HasColumnName("formatted_length");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bullish");

                    b.Property<bool?>("IsProfitableTrade")
                        .HasColumnType("boolean")
                        .HasColumnName("is_profitable_trade");

                    b.Property<bool?>("IsShort")
                        .HasColumnType("boolean")
                        .HasColumnName("is_short");

                    b.Property<bool?>("IsSwing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_swing");

                    b.Property<decimal?>("LastCheckedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("last_checked_price");

                    b.Property<decimal?>("LastKnownPercentProfit")
                        .HasColumnType("numeric")
                        .HasColumnName("last_known_percent_profit");

                    b.Property<string>("OptionsContractSymbol")
                        .HasColumnType("text")
                        .HasColumnName("options_contract_symbol");

                    b.Property<string>("OriginalExitMessage")
                        .HasColumnType("text")
                        .HasColumnName("original_exit_message");

                    b.Property<string>("OriginalMessage")
                        .HasColumnType("text")
                        .HasColumnName("original_message");

                    b.Property<decimal?>("PriceAtExit")
                        .HasColumnType("numeric")
                        .HasColumnName("price_at_exit");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("numeric")
                        .HasColumnName("price_paid");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Risk")
                        .HasColumnType("text")
                        .HasColumnName("risk");

                    b.Property<bool>("RiskApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("risk_approved");

                    b.Property<string>("RiskReason")
                        .HasColumnType("text")
                        .HasColumnName("risk_reason");

                    b.Property<string>("Side")
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<decimal?>("Strike")
                        .HasColumnType("numeric")
                        .HasColumnName("strike");

                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset?>("TimeOfEntryAlert")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_of_entry_alert");

                    b.Property<DateTimeOffset?>("TimeOfFullExitAlert")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_of_full_exit_alert");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<double?>("XScore")
                        .HasColumnType("double precision")
                        .HasColumnName("xscore");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_alerts_symbol");

                    b.HasIndex("TimeOfEntryAlert")
                        .HasDatabaseName("idx_alerts_time_of_entry");

                    b.HasIndex("UserName")
                        .HasDatabaseName("idx_alerts_username");

                    b.HasIndex("Side", "TimeOfEntryAlert")
                        .HasDatabaseName("idx_alerts_side_time");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Vela.Worker.Data.OpenPosition", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_id");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("entry_amount");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("entry_price");

                    b.Property<string>("Expiration")
                        .HasColumnType("text")
                        .HasColumnName("expiration");

                    b.Property<bool>("HasAveraged")
                        .HasColumnType("boolean")
                        .HasColumnName("has_averaged");

                    b.Property<bool>("IsAverage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_average");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("OptionsContract")
                        .HasColumnType("text")
                        .HasColumnName("options_contract");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StopOrderId")
                        .HasColumnType("text")
                        .HasColumnName("stop_order_id");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("stop_price");

                    b.Property<decimal?>("Strike")
                        .HasColumnType("numeric")
                        .HasColumnName("strike");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<string>("TargetOrderId")
                        .HasColumnType("text")
                        .HasColumnName("target_order_id");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("target_price");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trade_type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("OrderId");

                    b.ToTable("open_positions", (string)null);
                });

            modelBuilder.Entity("Vela.Worker.Data.TradeMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("AccountBalanceAtEntry")
                        .HasColumnType("numeric")
                        .HasColumnName("account_balance_at_entry");

                    b.Property<string>("AlertId")
                        .HasColumnType("text")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset>("AlertReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alert_received_at");

                    b.Property<decimal>("AlertedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("alerted_price");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("entry_amount");

                    b.Property<decimal?>("ExitAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("exit_amount");

                    b.Property<int?>("ExitLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("exit_latency_ms");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("exit_price");

                    b.Property<decimal?>("ExitSlippagePct")
                        .HasColumnType("numeric")
                        .HasColumnName("exit_slippage_pct");

                    b.Property<decimal>("ExposurePct")
                        .HasColumnType("numeric")
                        .HasColumnName("exposure_pct");

                    b.Property<decimal>("FillPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("fill_price");

                    b.Property<bool>("IsAverage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_average");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<decimal>("OpenPositionsValueAtEntry")
                        .HasColumnType("numeric")
                        .HasColumnName("open_positions_value_at_entry");

                    b.Property<string>("OptionsContract")
                        .HasColumnType("text")
                        .HasColumnName("options_contract");

                    b.Property<DateTimeOffset>("OrderFilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_filled_at");

                    b.Property<DateTimeOffset>("OrderSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_submitted_at");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("PnL")
                        .HasColumnType("numeric")
                        .HasColumnName("pnl");

                    b.Property<decimal?>("PnLPct")
                        .HasColumnType("numeric")
                        .HasColumnName("pnl_pct");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SlippagePct")
                        .HasColumnType("numeric")
                        .HasColumnName("slippage_pct");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("stop_price");

                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("target_price");

                    b.Property<string>("TradeType")
                        .HasColumnType("text")
                        .HasColumnName("trade_type");

                    b.Property<string>("TraderName")
                        .HasColumnType("text")
                        .HasColumnName("trader_name");

                    b.Property<decimal?>("XScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlertReceivedAt")
                        .HasDatabaseName("idx_trade_metrics_received_at");

                    b.HasIndex("ClosedAt")
                        .HasDatabaseName("idx_trade_metrics_closed_at");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_trade_metrics_symbol");

                    b.HasIndex("TraderName")
                        .HasDatabaseName("idx_trade_metrics_trader");

                    b.ToTable("trade_metrics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
